### ISSUE TITLE
[BUG] Problem with wallpapers 

### ISSUE THREAD

**Issue by mesteryui** [Alaory/WallMe-Wallpaper#15]
# Android 12 problems

In android 12 when I put a wallpaper the material you don't change color correctly 

## Android system

* Device: Redmi Note 9 Pro
* OS: LineageOS 19.1 based on Android 12

**Comment by mesteryui** [comment]
This happens me in few wallpae

**Comment by Alaory** [comment]
Did you resolve the issue?

**Comment by mesteryui** [comment]
I already don't know that
