### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by otheapache** [Alaory/WallMe-Wallpaper#19]
App crashes as soon as I try to save the wallpaper. I thought that the issue would have been fixed with the new update which added the new cool UI. App is really good.

**Comment by Alaory** [comment]
which version are you using?

**Comment by otheapache** [comment]
The latest one.

**Comment by Alaory** [comment]
by save the wallpaper you mean downloading it?

**Comment by otheapache** [comment]
Yes. That's exactly what I mean.

**Comment by Alaory** [comment]
Then that mean you are using the fdroid version... I did fix the issue in the new release however the fdroid version might take a bit of time to get updated:)

**Comment by otheapache** [comment]
Yes sir. I'm using the f-droid version and thanks for the heads-up. I appreciate the effort that you put into this beautiful, elegant yet simple and light app.
