### ISSUE TITLE
Downloading files crashes on a NZ507

### ISSUE THREAD

**Issue by csdvrx** [Alaory/WallMe-Wallpaper#22]
Everything works, except downloading a wallpaper.

You may be using a non-standard folder which would require permissions?

After checking the possible permissions:

icx1295:/ $ appops get com.alaory.wallmewallpaper
TOAST_WINDOW: allow; time=+6m52s279ms ago; duration=+4s24ms
READ_EXTERNAL_STORAGE: allow; time=+7m14s302ms ago
WRITE_EXTERNAL_STORAGE: allow; time=+7m14s302ms ago

Then trying to grant them:

255|icx1295:/ $ pm grant com.alaory.wallmewallpaper android.permission.WRITE_EXTERNAL_STORAGE
Security exception: Package com.alaory.wallmewallpaper has not requested permission android.permission.WRITE_EXTERNAL_STORAGE

appops reset doesn't help, as the problem seems to be the app hasn't requested permissions.

I would suggest you check https://developer.android.com/training/permissions/requesting and for kotlin https://stackoverflow.com/questions/71465812/how-to-get-permission-result-in-kotlin

**Comment by Alaory** [comment]
I am using Media Store which doesn't require storage premissions to save images and videos.. 

I still haven't tested it on all the android versions.

Is there a way for you to send the crash logs so i could look into it :)

**Comment by Alaory** [comment]
Ooops.. turns out to use media store on android Oreo and below it requires storage permission

Thanks for the issue.

**Comment by Alaory** [comment]
i fixed it... hopefully
