### ISSUE TITLE
Difficult to see text in dark mode

### ISSUE THREAD

**Issue by gbakeman** [Alaory/WallMe-Wallpaper#23]
I can't wait to start using this app, but I'm finding it difficult to read text on dark backgrounds. Hopefully the text color can be adjusted for dark mode.

![Screenshot_20221018-232035](https://user-images.githubusercontent.com/842942/196612248-e11a081c-a211-4700-b341-62100f626af9.jpg)

**Comment by Alaory** [comment]
what is your android version?

**Comment by gbakeman** [comment]
Fwiw I'm on Android 9, but I see you've marked this as fixed, so thank you!
