### ISSUE TITLE
Export/Import option

### ISSUE THREAD

**Issue by cu1tur4l** [Alaory/WallMe-Wallpaper#27]
Hello. It's me again.

I'm reseting my phone completely and I'd love to export already hearted photos, for obvious reasons. If you have time - and this is easy enough - could you add such option asap? 
I'm so sorry for requesting it in a such selfish way, but my files are behaving very strangely (in terms of copying, moving, sometimes creating), so I would love to reset my phone also asap. 

Hope sleeping is going well 😄

**Comment by Alaory** [comment]
Well actually i was thinking of that since i keep developing i keep on losing my favorite wallpapers. I am gonna add that but i got no idea on how to do it. Hopefully i am gonna add it in the coming days
