### ISSUE TITLE
I do not see an option to set the selected wallpaper

### ISSUE THREAD

**Issue by Moxville** [Alaory/WallMe-Wallpaper#29]
Thanks for the nice App.

moto g82 5g
Android 12
wallme Wallpaper 2.53

I selected a wallpaper but I do not see any option to set the wallpaper for "Home Screen, Lock Screen, Both"
Am I missing something ?

![Screenshot_20230114-185234](https://user-images.githubusercontent.com/31923265/212474703-01ce9859-3824-4a3f-a7d9-722c10e04904.png)

**Comment by Alaory** [comment]
Its under your navigation. I still don't know how to fix it on all devices 🙃

**Comment by Moxville** [comment]
Thanks a lot. Now I see the menu.
Is it possible to bring "set as wallpaper" on top of the screen / little higher from bottom of the screen ?
A "close" button would also be nice on the popup window

![Screenshot_20230115-100623](https://user-images.githubusercontent.com/31923265/212523270-37bed011-af89-4fd5-81eb-4752fc37f1ef.png)

**Comment by Alaory** [comment]
Huh i never thought of that. I might add it in the future
