### ISSUE TITLE
Add Unsplash support

### ISSUE THREAD

**Issue by mikjori** [Alaory/WallMe-Wallpaper#3]
It would be nice if you could add Unsplash support in the near future. They have a nice API to work with.

**Comment by Alaory** [comment]
I'll look into it

**Comment by Alaory** [comment]
i might add it in the future

**Comment by Alaory** [comment]
i won't be adding support for Unsplash since my app is open source , Unsplash requires a an API key and the app violate their guide line 

```

🚫 a wallpaper app returns Unsplash images for downloading. Without the integration, the app has no content and no value to users.

Your Access Key and Secret Key must remain confidential. 

```
