### ISSUE TITLE
Bug: porn filter blocking EarthPorn?

### ISSUE THREAD

**Issue by pnrao** [Alaory/WallMe-Wallpaper#34]
You probably have setup some filters against NSFW content. However, https://www.reddit.com/r/EarthPorn/ is an excellent source of clean, SFW images, and I can't add it as a source. Can you please fix this?

**Comment by Alaory** [comment]
I can't work on the app now i have some problems with my computer. When i fix it i try to work on it :)

**Comment by lrq3000** [comment]
Still can't add EarthPorn subreddit. Please add an option to remove all filters, censorship filters should never be forced onto the user anyway.
