### ISSUE TITLE
Reddit images not loading 

### ISSUE THREAD

**Issue by AnuAYA** [Alaory/WallMe-Wallpaper#35]
An load button is showing but nothing is happening even after tapping
 it.https://github.com/Alaory/WallMe-Wallpaper/assets/94795742/30ec0d87-7615-4573-8af4-092541351c27

**Comment by Alaory** [comment]
Which version are you using. fdroid or GitHub?

**Comment by AnuAYA** [comment]
fdroid

**Comment by AnuAYA** [comment]
I cleared my cache and it seems to be working now.
