### ISSUE TITLE
Touch buttons covering the menus in the app

### ISSUE THREAD

**Issue by siva-sub** [Alaory/WallMe-Wallpaper#9]
![Screenshot_2022-09-14-22-59-28-284_com alaory wallmewallpaper](https://user-images.githubusercontent.com/109394658/190191112-30f3efcd-5df9-4892-be4d-a09ffab099b6.jpg)

The device I am using is Poco f4 GT and it is running miui 13(android 12). The app is still usable but it would be better if the in-app buttons can avoid the navigation buttons.

Also thanks for developing this app was looking for something similar to the linux app, variety wallpaper for my mobile phone for a while and this fully satisfies the need.

**Comment by Alaory** [comment]
I alright I'll work on it tomorrow

**Comment by Alaory** [comment]
![Uploading Screenshot_20220914_182339_com.alaory.wallmewallpaper.jpg…]()

Does your home screen navigation buttons look like this?

**Comment by Alaory** [comment]
![Screenshot_20220914_182339_com.alaory.wallmewallpaper.jpg](https://user-images.githubusercontent.com/50534770/190207564-3d0d06cb-295d-4229-9cdf-ad144eb0a357.jpg)

Does your main navigation buttons look like this?

**Comment by siva-sub** [comment]
Yep my main navigation looks like that too 


![Screenshot_2022-09-14-22-59-34-191_com alaory wallmewallpaper](https://user-images.githubusercontent.com/109394658/190212474-119dbefe-6cba-4657-93d2-a6ee21cfba5a.jpg)

**Comment by Alaory** [comment]
Ok you get the double major bug i'll try fix it ASAP

**Comment by Alaory** [comment]
i fixed the issue in the new release
you can check it out: https://github.com/Alaory/WallMe-Wallpaper/releases/latest

**Comment by siva-sub** [comment]
![Screenshot_2022-09-15-02-53-33-066_com alaory wallmewallpaper](https://user-images.githubusercontent.com/109394658/190238996-826f6d86-743d-48ac-a959-7ff8caf9676e.jpg)
![Screenshot_2022-09-15-02-53-30-020_com alaory wallmewallpaper](https://user-images.githubusercontent.com/109394658/190239007-2030efb1-ce27-4cb6-a839-1d4d6a1b86af.jpg)
![Screenshot_2022-09-15-02-53-18-169_com alaory wallmewallpaper](https://user-images.githubusercontent.com/109394658/190239024-fe754f84-3b8b-4687-8c27-0eb7e1d68b75.jpg)

Wow, thanks for the fast fix man. It works
